apiVersion: v1
kind: ConfigMap
metadata:
  name: containerd-registry-mirrors
  namespace: ${namespace}
data:
  registries.yaml: |
    mirrors:
      docker.io:
        endpoint:
          - https://${harbor_fqdn}/v2/proxy-docker.io
      quay.io:
        endpoint:
          - https://${harbor_fqdn}/v2/proxy-quay.io
      ghcr.io:
        endpoint:
          - https://${harbor_fqdn}/v2/proxy-ghcr.io
      registry.k8s.io:
        endpoint:
          - https://${harbor_fqdn}/v2/proxy-k8s.io
    configs:
      "${harbor_fqdn}":
        tls:
          ca_file: /usr/local/share/ca-certificates/harbor_cert.pem
          insecure_skip_verify: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: configure-containerd-mirrors
  namespace: ${namespace}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: configure-containerd-mirrors
  template:
    metadata:
      labels:
        app: configure-containerd-mirrors
    spec:
      initContainers:
      - name: configure-containerd
        image: busybox
        command:
          - /bin/sh
          - -c
          - |
            set -e
            echo "Configuring k3s containerd registry mirrors..."
            mkdir -p /host/etc/rancher/k3s
            echo "Copying k3s registry mirror configurations..."
            cp /config/registries.yaml /host/etc/rancher/k3s/registries.yaml
            echo "Adding harbor CA certificate to host trust store..."
            cp /certs/harbor_cert.pem /usr/local/share/ca-certificates/harbor_cert.pem
            echo "k3s containerd registry mirrors configured, now restart k3s manually to apply the new configuration. You can do this by running 'sudo systemctl restart k3s' or k3s-agent on each node in the cluster."
            echo "Done."
        securityContext:
          runAsUser: 0
        volumeMounts:
          - name: host-k3s-config
            mountPath: /host/etc/rancher/k3s
          - name: host-ca-certs
            mountPath: /usr/local/share/ca-certificates
          - name: config
            mountPath: /config
            readOnly: true
          - name: harbor-ca-cert
            mountPath: /certs
            readOnly: true
      containers:
        - name: wait
          image: registry.k8s.io/pause:3.8
          resources:
            requests:
              cpu: 10m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 50Mi
          securityContext:
            privileged: false
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        - name: host-k3s-config
          hostPath:
            path: /etc/rancher/k3s
            type: DirectoryOrCreate
        - name: host-ca-certs
          hostPath:
            path: /usr/local/share/ca-certificates
            type: Directory
        - name: config
          configMap:
            name: containerd-registry-mirrors
        - name: harbor-ca-cert
          configMap:
            name: harbor-ca-cert
